version: "3"

services:
  postgres:
    image: postgres
    volumes:
      - ./psql_dump.sql:/docker-entrypoint-initdb.d/psql_dump.sql
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    ports:
      - 9200:9200

  logstash:
    build: .
    ports:
      - 9600:9600
    depends_on:
      - elasticsearch
